### ISSUE TITLE
Where to submit a Translation

### ISSUE THREAD

**Issue by tinygrox** [AniruddhKSP/KSP-Beamed-Power-Standalone-mod#2]
Where should I upload a translation file?
I have completed the Chinese translation.
[zh-cn.zip](https://github.com/AniruddhKSP/KSP-Beamed-Power-Standalone-mod/files/11297267/zh-cn.zip)

**Comment by AniruddhKSP** [comment]
Idk actually i havent seen how other modders handle this. Its upto you how you want to do it. Either i can add it to the install itself in the localisation folder and give you credit, or you can post a link on a forums post in the Beamed Power thread.

**Comment by tinygrox** [comment]
> Either i can add it to the install itself in the localisation folder and give you credit, or you can post a link on a forums post in the Beamed Power thread.

**I prefer the former.**

> Idk actually i havent seen how other modders handle this.

Other mods like KSPIE, Near Future, have a **GameData** folder for release on github([KSPIE](https://github.com/sswelm/KSP-Interstellar-Extended/tree/master/GameData) | [Near Future Exploration](https://github.com/post-kerbin-mining-corporation/NearFutureExploration/tree/master/GameData/NearFutureExploration)), which contains all the translations. Therefore, for changes in translation, others only need to pull a request like this https://github.com/sswelm/KSP-Interstellar-Extended/pull/555

**Comment by AniruddhKSP** [comment]
Is what i have done sufficient? Id rather not create a new release, but you should still be able to submit a pull request now for zh-cn.cfg in Localization/

**Comment by tinygrox** [comment]
Yep, now the mod can support more languages in the future. and this issue can be closed.😄
